"""add_chat_views_and_citations

Revision ID: 01958034948b
Revises: b88fbf04fdd9
Create Date: 2026-07-20 23:39:48.240397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01958034948b'
down_revision: Union[str, Sequence[str], None] = 'b88fbf04fdd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Read-only, user-scoped views for the chatbot's NL->SQL execution path
# (chat/orchestration/sql_execution.py). Each filters on a session-local
# setting rather than a bind parameter, so a query has no way to see another
# user's rows regardless of what the LLM generates -- the caller always runs
# `SET LOCAL app.chat_user_id = '<uuid>'` before executing the LLM's SQL.
# `current_setting(..., true)` returns NULL rather than erroring when unset,
# which fails closed (zero rows) instead of leaking everything.
_CHAT_USER_FILTER = "current_setting('app.chat_user_id', true)::uuid"

_VIEWS: list[tuple[str, str]] = [
    (
        "v_transactions",
        f"""
        CREATE VIEW v_transactions AS
        SELECT
            t.id,
            t.user_id,
            t.merchant_name,
            t.description,
            t.amount,
            t.currency,
            t.transaction_date,
            t.authorized_date,
            t.pending,
            t.category,
            t.payment_channel,
            ta.normalized_merchant,
            ta.normalized_category,
            ta.fraud_score,
            ta.smart_purchase_score,
            ta.price_competitiveness_score,
            ta.behavioral_score,
            ta.anomaly_score,
            ta.merchant_frequency,
            ta.category_monthly_average,
            ta.spending_deviation
        FROM transactions t
        LEFT JOIN transaction_analysis ta ON ta.transaction_id = t.id
        WHERE t.removed_at IS NULL AND t.user_id = {_CHAT_USER_FILTER}
        """,
    ),
    (
        "v_subscriptions",
        f"""
        CREATE VIEW v_subscriptions AS
        SELECT
            id, user_id, merchant_name, normalized_name, average_cost, currency,
            billing_cycle, last_charge, next_expected_charge,
            last_price_change_amount, status
        FROM subscriptions
        WHERE user_id = {_CHAT_USER_FILTER}
        """,
    ),
    (
        "v_insights",
        f"""
        CREATE VIEW v_insights AS
        SELECT
            id, user_id, type, title, description, severity, category,
            confidence, created_at, viewed_at, dismissed_at, expires_at
        FROM insights
        WHERE user_id = {_CHAT_USER_FILTER}
        """,
    ),
    (
        "v_bank_accounts",
        f"""
        CREATE VIEW v_bank_accounts AS
        SELECT
            id, user_id, institution_name, account_name, account_type,
            account_subtype, current_balance, available_balance, currency,
            last_sync
        FROM bank_accounts
        WHERE deleted_at IS NULL AND user_id = {_CHAT_USER_FILTER}
        """,
    ),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('citations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

    for _, view_sql in _VIEWS:
        op.execute(view_sql)


def downgrade() -> None:
    """Downgrade schema."""
    for view_name, _ in reversed(_VIEWS):
        op.execute(f"DROP VIEW IF EXISTS {view_name}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'citations_json')
    # ### end Alembic commands ###
