"""add_gemini_usage_daily

Revision ID: 93f5946eaba0
Revises: cffe18ed0443
Create Date: 2026-07-21 06:19:46.881314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f5946eaba0'
down_revision: Union[str, Sequence[str], None] = 'cffe18ed0443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gemini_usage_daily',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gemini_usage_daily')
    # ### end Alembic commands ###
