"""add_category_to_insights

Revision ID: b88fbf04fdd9
Revises: ff3453b38457
Create Date: 2026-07-13 12:35:12.244302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88fbf04fdd9'
down_revision: Union[str, Sequence[str], None] = 'ff3453b38457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('category', sa.String(), nullable=True))
    op.create_index(op.f('ix_insights_category'), 'insights', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_category'), table_name='insights')
    op.drop_column('insights', 'category')
    # ### end Alembic commands ###
