"""add subscriptions, merchant_profiles, transaction_analysis, insights, embeddings, chat_sessions, chat_messages

Revision ID: ff3453b38457
Revises: aa73e46844fd
Create Date: 2026-07-04 21:33:06.662223

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff3453b38457'
down_revision: Union[str, Sequence[str], None] = 'aa73e46844fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_profiles',
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('merchant_type', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('embeddings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('object_type', sa.Enum('TRANSACTION', 'MERCHANT', 'INSIGHT', 'CHAT_MESSAGE', name='embeddingobjecttype', native_enum=False), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_object_id'), 'embeddings', ['object_id'], unique=False)
    op.create_index(op.f('ix_embeddings_user_id'), 'embeddings', ['user_id'], unique=False)
    op.create_table('insights',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_user_id'), 'insights', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('average_cost', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('billing_cycle', sa.String(), nullable=False),
    sa.Column('last_charge', sa.Date(), nullable=True),
    sa.Column('next_expected_charge', sa.Date(), nullable=True),
    sa.Column('last_price_change_amount', sa.Numeric(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'PAUSED', name='subscriptionstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('sql_generated', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('transaction_analysis',
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('normalized_merchant', sa.String(), nullable=True),
    sa.Column('normalized_category', sa.String(), nullable=True),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('fraud_score', sa.Numeric(), nullable=True),
    sa.Column('fraud_reason', sa.String(), nullable=True),
    sa.Column('smart_purchase_score', sa.Numeric(), nullable=True),
    sa.Column('price_competitiveness_score', sa.Numeric(), nullable=True),
    sa.Column('behavioral_score', sa.Numeric(), nullable=True),
    sa.Column('anomaly_score', sa.Numeric(), nullable=True),
    sa.Column('merchant_frequency', sa.Numeric(), nullable=True),
    sa.Column('category_monthly_average', sa.Numeric(), nullable=True),
    sa.Column('spending_deviation', sa.Numeric(), nullable=True),
    sa.Column('analysis_version', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_analysis_subscription_id'), 'transaction_analysis', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_transaction_analysis_transaction_id'), 'transaction_analysis', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_foreign_key(
        'fk_transactions_merchant_id_merchant_profiles',
        'transactions', 'merchant_profiles', ['merchant_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_transactions_merchant_id_merchant_profiles', 'transactions', type_='foreignkey'
    )
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transaction_analysis_transaction_id'), table_name='transaction_analysis')
    op.drop_index(op.f('ix_transaction_analysis_subscription_id'), table_name='transaction_analysis')
    op.drop_table('transaction_analysis')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_insights_user_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_embeddings_user_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_object_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_table('merchant_profiles')
    # ### end Alembic commands ###
